# Generated by Django 4.2.18 on 2025-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerbasket_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementlog',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
