# Generated by Django 4.2.18 on 2025-01-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_customerbasket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbasket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='core.customer'),
        ),
    ]
